### ISSUE TITLE
iOS7 Compat.

### ISSUE THREAD

**Issue by StuartMorris0** [leonardoobaptistaa/FeedbackMe#2]
Hello,

I also found that this appears to be iOS8 + compatible. Was this intended?

It looks like containsString is only available in iOS8 +. As far as I can tell that is the only issue, you can update that to use a range check in iOS7 to at least support that.

I have a fork with that in, is there anything else that could affect iOS7?

Thanks

**Comment by leonardoobaptistaa** [comment]
Hi @StuartMorris0 

The iOS8+ thing was just to keep it simple, but will be nice support iOS7 too.
I can't remember anything else that could affect, but I have to test it. 
This project have some unit tests, are they passing on iOS7 Simulator?

Probably I won't be able to check this issue this week, but it is a great add on.

**Comment by leonardoobaptistaa** [comment]
Hey @StuartMorris0 

Can you open a pull request?
I will merge on master as soon as possible.

Thanks!

**Comment by StuartMorris0** [comment]
Sorry on the late reply, was you able to get that added or still after the code?

**Comment by leonardoobaptistaa** [comment]
Yes, please.
Can you open a pull request?

**Comment by StuartMorris0** [comment]
Sorry on the delay

https://github.com/leonardoobaptistaa/FeedbackMe/pull/3
